config/routes.rb
CTAttendance::Application.routes.draw do

  resources :allowed_ips

  root 'attendances#index'

  devise_scope :employees do
    get "admin" => "registrations#new"
  end

  resources :attendances do
    collection do
      get :make_leave
      get :by_name
      get :by_date
    end
    member do
      post :create_leave
    end
  end

  devise_for :employees, :controllers => { registrations: 'registrations' }

end

app/models/allowed_ip.rb
class AllowedIp < ActiveRecord::Base
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :date, presence: true
  # validates :login_at, presence: true
  # validates :present, presence: true
  # validates :leave, presence: true
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, password_length: 6..128

  def timeout_in
    10.hours
  end
  # validates :firstname, presence: true
  # validates :lastname, presence: true
  # validates :admin, presence: true

end

app/controllers/allowed_ips_controller.rb
class AllowedIpsController < ApplicationController
  before_action :set_allowed_ip, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @allowed_ips = AllowedIp.all
    respond_with(@allowed_ips)
  end

  def show
    respond_with(@allowed_ip)
  end

  def new
    @allowed_ip = AllowedIp.new
    respond_with(@allowed_ip)
  end

  def edit
  end

  def create
    @allowed_ip = AllowedIp.new(allowed_ip_params)
    if @allowed_ip.save
      redirect_to root_path
    end
  end

  def update
    @allowed_ip.update(allowed_ip_params)
    respond_with(@allowed_ip)
  end

  def destroy
    @allowed_ip.destroy
    respond_with(@allowed_ip)
  end

  private
    def set_allowed_ip
      @allowed_ip = AllowedIp.find(params[:id])
    end

    def allowed_ip_params
      params.require(:allowed_ip).permit(:name, :ip_address)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :block_foreign_ip
  before_filter :authenticate_employee!
  before_filter :set_cache_buster
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def white_listed?(ip)
    @allowed_ip = AllowedIp.all
    @white_list = Array.new
    @allowed_ip.each do |ip|
      @white_list.push(ip.ip_address)
    end
    return true if @white_list.include?(ip)
    # return true if ["127.0.5.1", "127.0.0.1"].include?(ip)
    false
  end

  def block_foreign_ip
    redirect_to "http://www.coderstrust.com" unless white_listed?(request.remote_ip)
  end


  def after_sign_in_path_for(resource)

    $absent = Array.new

    @employee = Employee.all()
    date = Time.now.strftime("%d %B %Y").to_s
    @attendances_today = Attendance.where(:date => date )

    @employee.each do |emp|
      @present = false
      @attendances_today.each do |a|
        if emp.email == a.email
          @present = true
        end
      end
      if @present == false
        $absent.push(emp)
      end
    end

    present = true
    if $absent != nil
      $absent.each do |ab|
        if ab.email == current_employee.email
          present = false
          break
        end
      end
    end

    if present == false
      new_attendance_path
    else
      root_path
    end

  end


  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end


end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  respond_to :html
  def index
    @attendance = Attendance.new
    $absent = Array.new
    @employee = Employee.all()

    date = Time.now.strftime("%d %B %Y").to_s
    @attendances = Attendance.all
    @attendances_today = @attendances.where(:date => date)
    @present_today = @attendances.where(:date => date).where(:leave => false)
    @on_leave = @attendances.where(:date => date).where(:leave => true)

    @employee.each do |emp|
      @present = false
      @attendances_today.each do |a|
        if emp.email == a.email
          @present = true
        end
      end
      if @present == false
        $absent.push(emp)
      end
    end
    # respond_with(@attendances)
  end

  def show
    respond_with(@attendance)
  end

  def new
    @attendance = Attendance.new
    respond_with(@attendance)
  end

  def edit
  end

  def create
    @attendance = Attendance.new(attendance_params)

    if @attendance.save
     redirect_to root_path
    else
      redirect_to new_attendance_path
    end
  end

  def update
    if @attendance.email == current_employee.email
      if @attendance.update_attribute(:logout_at, Time.now+6.hours)
        # sign_out
        redirect_to root_path
      end
    elsif @attendance.email != current_employee.email
      if @attendance.update(attendance_params)
        redirect_to root_path
      end
    end
  end

  def destroy
    @attendance.destroy
    respond_with(@attendance)
  end

  def by_name
    email = params[:email]
    if email.present?
      start_date = DateTime.parse(params["start_date"].values.join("-"))
      end_date = DateTime.parse(params["end_date"].values.join("-"))
    end
    @attendances = Attendance.all
    @report_by_name = @attendances.where(created_at:  start_date..end_date).where(:email => email)
    @leave_count = @report_by_name.where(:leave => true).count
    # @present_today = @attendances.where(:date => date).where(:leave => false)
  end

  def by_date
    date = params[:start_date]
    if date.present?
      start_date = DateTime.parse(params["start_date"].values.join("-"))
      end_date = DateTime.parse(params["end_date"].values.join("-"))
    end
    @report_by_date = Attendance.where(created_at:  start_date..end_date)
  end

  def make_leave
    @employee = Employee.find(params[:e_id])
    @attendance = Attendance.new
    respond_with(@attendance)
  end

  def create_leave
    @attendance = Attendance.new(attendance_params)
    if @attendance.save
      redirect_to root_path
    else
      redirect_to new_attendance_path
    end

  end

  private
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    def attendance_params
      params.require(:attendance).permit(:firstname, :lastname, :email, :date.to_s, :login_at, :logout_at, :present, :leave, :leave_cause)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def destroy
    @employee = Employee.find(params[:id])

    if @employee.destroy
      redirect_to root_path
    end
  end

  private
  def sign_up_params
    params.require(:employee).permit(:firstname, :lastname, :admin, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:employee).permit(:firstname, :lastname, :admin, :email, :password, :password_confirmation, :current_password)
  end


end

app/helpers/absent_helper.rb
module AbsentHelper
end

app/helpers/allowed_i_ps_helper.rb
module AllowedIPsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/allowed_ips/_form.html.erb
<%= form_for(@allowed_ip) do |f| %>
  <% if @allowed_ip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@allowed_ip.errors.count, "error") %> prohibited this allowed_ip from being saved:</h2>

      <ul>
      <% @allowed_ip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br>
    <%= f.text_field :ip_address %>
  </div>
  <div class="actions">
    <%= f.submit "Allow This IP", :class => "btn btn-default", :style => "width: 100%" %>
  </div>
<% end %>

app/views/allowed_ips/_header.html.erb
<div class="row-fluid">
  <div class="span3">
    <%= image_tag "ct_logo.png", :style => "margin:8% 0 0 5%" %>
    <b style="margin-left: 6%; font-size: 16px"><%= Time.now.strftime("%A, %d %B %Y") %></b>
  </div>

  <div class="span7" style="margin-top: 1%">
    <div class="row-fluid" style="display: inline-flex">
      <div class="span2"><%= link_to "Home", root_path, :class => "btn btn-default", :style => "margin-left:15%" %></div>
      <div class="span8>">
        <%= link_to "Individual Report", {:controller => :attendances, :action => :by_name}, :class => "btn btn-default" %>
        <%= link_to "Report By Date", {:controller => :attendances, :action => :by_date}, :class => "btn btn-default" %>
        <% if current_employee.admin %>
            <%= link_to "Add IP", {:controller => :allowed_ips, :action => :new}, :class => "btn btn-default" %>
            <%= link_to "View IP", {:controller => :allowed_ips, :action => :index}, :class => "btn btn-default" %>
        <% end %>
      </div>
      <div class="span2">

      </div>
    </div>
  </div>
  <div class="span2">
    Welcome, <b><%= current_employee.firstname %> <%= current_employee.lastname %></b>
    <%= link_to "signout", destroy_employee_session_path, :method => :delete %>
    <% if current_employee.admin %>
        Admin
    <% end %>
  </div>
</div>
<hr>

app/views/allowed_ips/edit.html.erb
<h1>Editing allowed_ip</h1>

<%= render 'form' %>

<%= link_to 'Show', @allowed_ip %> |
<%= link_to 'Back', allowed_ips_path %>

app/views/allowed_ips/index.html.erb
<div>
  <%= render 'header' %>

  <div class="row-fluid">
    <div class="span3"></div>
    <div class="span2"><b>Name</b></div>
    <div class="span2"><b>IP Address</b></div>
    <div class="span2"><b>Actions</b></div>
    <div class="span3"></div>
  </div>

</div>

<div>

    <% @allowed_ips.each do |allowed_ip| %>
      <div class="row-fluid">
        <div class="span3"></div>
        <div class="span2"><%= allowed_ip.name %></div>
        <div class="span2"><%= allowed_ip.ip_address %></div>
        <div class="span2"><%= link_to 'Destroy', allowed_ip, method: :delete, data: { confirm: 'Are you sure?' } %></div>
        <div class="span3"></div>
      </div>
    <% end %>


</div>

app/views/allowed_ips/new.html.erb
<div>
  <%= render 'header' %>
  <div class="row-fluid">
    <div class="span5"></div>
    <div class="span2">
      <h2 style="text-align: center">Add New IP Address</h2>

      <%= render 'form' %>

    </div>
    <div class="span5"></div>
  </div>
</div>

app/views/allowed_ips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @allowed_ip.name %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @allowed_ip.ip_address %>
</p>

<%= link_to 'Edit', edit_allowed_ip_path(@allowed_ip) %> |
<%= link_to 'Back', allowed_ips_path %>

app/views/attendances/_form.html.erb
<%= form_for(@attendance) do |f| %>
    <% if @attendance.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

          <ul>
            <% @attendance.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.hidden_field :firstname, :value => current_employee.firstname %>
    </div>
    <div class="field">
      <%= f.hidden_field :lastname, :value => current_employee.lastname %>
    </div>
    <div class="field">
      <%= f.hidden_field :email, :value => current_employee.email %>
    </div>
    <div class="field">
      <% date = Time.now.strftime("%d %B %Y").to_s %>
      <%= f.hidden_field :date, :value => date %>
    </div>
    <div class="field">
      <%= f.hidden_field :login_at, :value => Time.now %>
    </div>
    <div class="field">
      <%= f.hidden_field :logout_at %>
    </div>
    <div class="field">
      <%= f.hidden_field :present, :value => true %>
    </div>
    <div class="field">
      <%= f.hidden_field :leave, :value => false %>
    </div>
    <div class="field">
      <%= f.hidden_field :leave_cause %>
    </div>
    <div class="actions">
      <%= f.submit "Check in", :class => "btn btn-default"%>
    </div>
<% end %>

app/views/attendances/_header.html.erb
<div class="row-fluid">
  <div class="span3">
    <%= image_tag "ct_logo.png", :style => "margin:8% 0 0 5%" %>
    <b style="margin-left: 6%; font-size: 16px"><%= Time.now.strftime("%A, %d %B %Y") %></b>
  </div>

  <div class="span7" style="margin-top: 1%">
    <div class="row-fluid" style="display: inline-flex">
      <div class="span2"><%= link_to "Home", root_path, :class => "btn btn-default", :style => "margin-left:15%" %></div>
      <div class="span8>">
        <%= link_to "Individual Report", {:controller => :attendances, :action => :by_name}, :class => "btn btn-default" %>
        <%= link_to "Report By Date", {:controller => :attendances, :action => :by_date}, :class => "btn btn-default" %>
      </div>
      <div class="span2"></div>
    </div>
  </div>
  <div class="span2">
    Welcome, <b><%= current_employee.firstname %> <%= current_employee.lastname %></b>
    <%= link_to "signout", destroy_employee_session_path, :method => :delete %>
    <% if current_employee.admin %>
        Admin
    <% end %>
  </div>
</div>

app/views/attendances/by_date.html.erb
<div>
  <%= render 'header' %>
  <hr>
  <div class="row-fluid">
    <div class="span4"></div>
    <div class="span5">
      <%= form_tag({:controller => :attendances, :action => :by_date}, :method => "get") do %>
          <p><b>From</b></p>
          <%= date_select "start_date", nil%>
          <p><b>To</b></p>
          <%= date_select "end_date", nil %>
          <br><br>
          <%= submit_tag "Search",:class => "btn btn-default", :style => "margin-top:-1.5%; width:65%" %>
      <% end %>
    </div>
    <div class="span3"></div>
  </div>
  <hr>
  <div class="row-fluid">
    <div class="span2"><b>Firstname</b></div>
    <div class="span2"><b>Lastname</b></div>
    <div class="span2"><b>Date</b></div>
    <div class="span2"><b>Checked in at</b></div>
    <div class="span2"><b>Checked out at</b></div>
    <div class="span2"><b>Worked Hours</b></div>
  </div>
</div>
<% @report_by_date.each do |n| %>
    <div class="row-fluid">
      <div class="span2"><%= n.firstname %></div>
      <div class="span2"><%= n.lastname %></div>
      <div class="span2"><%= n.date %></div>
      <div class="span2">
        <% if n.login_at.present? %>
            <%= n.login_at.strftime("%H:%M") %>
        <% elsif n.leave %>
            was on <%= n.leave_cause %>
        <% end %>
      </div>
      <% if n.logout_at != nil %>
          <div class="span2"><%= n.logout_at.strftime("%H:%M") %></div>
          <% @hour = ((n.logout_at - n.login_at)/1.hours).floor %>
          <% @min = (((n.logout_at - n.login_at)%1.hours)/1.minutes).ceil %>
          <div class="span2"><%= @hour %> hours and <%= @min %> minutes</div>
      <% else %>
          <div class="span2"></div>
          <div class="span2"></div>
      <% end %>

    </div>

<% end %>

app/views/attendances/by_name.html.erb
<div>
  <%= render 'header' %>
  <hr>
  <div class="row-fluid">
    <div class="span4"></div>
    <div class="span5">
      <%= form_tag({:controller => :attendances, :action => :by_name}, :method => "get") do %>
          <p><b>From</b></p>
          <%= date_select "start_date", nil%>
          <p><b>To</b></p>
          <%= date_select "end_date", nil %>
          <p></p>
          <%= text_field_tag "email", nil, :placeholder => "Email Address" %>
          <%= submit_tag "Search",:class => "btn btn-default", :style => "margin-top:-2%; width:24%" %>
      <% end %>
    </div>
    <div class="span3"></div>
  </div>
  <hr>
  <div class="row-fluid">
    <div class="span1"><b>Firstname</b></div>
    <div class="span1"><b>Lastname</b></div>
    <div class="span2"><b>Date</b></div>
    <div class="span2"><b>Checked in at</b></div>
    <div class="span2"><b>Checked out at</b></div>
    <div class="span2"><b>Worked Hours</b></div>
    <div class="span2"><b>Options</b></div>
  </div>
</div>
<% @total_time = 0 %>
<% @report_by_name.each do |n| %>
    <div class="row-fluid">
      <div class="span1"><%= n.firstname %></div>
      <div class="span1"><%= n.lastname %></div>
      <div class="span2"><%= n.date %></div>
      <div class="span2">
        <% if n.login_at.present? %>
          <%= n.login_at.strftime("%H:%M") %>
        <% elsif n.leave %>
          was on <%= n.leave_cause %>
        <% end %>
      </div>
      <div class="span2">
          <% if n.logout_at != nil %>
              <%= n.logout_at.strftime("%H:%M") %>
              <% @total_time = ( @total_time + (n.logout_at - n.login_at)) %>
              <% @hour = ((n.logout_at - n.login_at)/1.hours).floor %>
              <% @min = (((n.logout_at - n.login_at)%1.hours)/1.minutes).ceil %>
          <% end %>
      </div>
      <div class="span2">
        <% if n.logout_at != nil %>
            <%= @hour %> hours and <%= @min %> minutes
        <% end %>
      </div>

      <div class="span2">
        <% if current_employee.admin && current_employee.email != n.email %>
            <%= link_to 'Edit', edit_attendance_path(n) %>
            <%= link_to 'Delete', n, method: :delete, data: { confirm: 'You are going to destroy the record!!! Are you sure?' } %>
        <% end %>
      </div>

    </div>

<% end %>

<br>
<hr>
<div class="row-fluid">
  <div class="span4"></div>
  <div class="span3">
    <b>Leave Count: </b> <%= @leave_count %>
  </div>
  <div class="span5">
    <% @t_hours = (@total_time/1.hours).floor %>
    <% @t_mins = ((@total_time%1.hours)/1.minutes).ceil %>
    <b>Total worked hours: </b> <%= @t_hours %> hours and <%= @t_mins %> minutes.
  </div>
</div>

app/views/attendances/edit.html.erb
<h1>Editing attendance</h1>

<%= form_for(@attendance) do |f| %>
    <% if @attendance.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

          <ul>
            <% @attendance.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.text_field :firstname, :readonly => true %>
    </div>
    <div class="field">
      <%= f.text_field :lastname, :readonly => true %>
    </div>
    <div class="field">
      <%= f.text_field :email, :readonly => true %>
    </div>
    <div class="field">
      <%= f.text_field :date, :readonly => true %>
    </div>
    <div class="field">
      <%= f.time_select :login_at %>
    </div>
    <div class="field">
      <%= f.time_select :logout_at %>
    </div>
    <div class="field">
      <%= f.hidden_field :present, :value => true %>
    </div>
    <div class="field">
      <%= f.hidden_field :leave, :value => false %>
    </div>
    <div class="field">
      <%= f.hidden_field :leave_cause %>
    </div>
    <div class="actions">
      <%= f.submit "Update" %>
    </div>
<% end %>


<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<div>
  <%= render 'header' %>
  <hr>

  <div style="margin-left: 1%">
    <div class="row-fluid">
      <div class="span2"></div>
      <div class="span10">
        <h2>Present Employees</h2>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span2"></div>
      <div class="span1"><b>Firstname</b></div>
      <div class="span1"><b>Lastname</b></div>
      <div class="span1"><b>Login At</b></div>
      <div class="span1"><b>Logout At</b></div>
      <div class="span2"></div>
      <div class="span2"><b>Total worked hours</b></div>
      <div class="span2"></div>
    </div>

    <% @present_today.each do |present| %>
        <div class="row-fluid">
          <div class="span2"></div>
          <div class="span1"><%= present.firstname %></div>
          <div class="span1"><%= present.lastname %></div>

          <div class="span1">
              <% if present.login_at.present? %>
                  <%= present.login_at.strftime("%H:%M") %>
              <% end %>
          </div>

          <div class="span1">
          <% if present.logout_at.present? %>
              <%= present.logout_at.strftime("%H:%M") %>
              <% @hour = ((present.logout_at - present.login_at)/1.hours).floor %>
              <% @min = (((present.logout_at - present.login_at)%1.hours)/1.minutes).ceil %>
          <% end %>
          </div>

          <div class="span2">
            <% if present.email == current_employee.email %>
              <% @out = Time.now %><%= link_to "Check out", attendance_path(present), :method => :put, :class => "btn btn-default", data: { confirm: 'You are going to end your office hour for today! Are you sure?' } %>
            <% end %>
          </div>

          <div class="span2">
            <% if present.logout_at != nil %>
                <%= @hour %> hours and <%= @min %> minutes
            <% end %>
          </div>


          <% if current_employee.admin && current_employee.email != present.email %>
              <div class="span2">
                    <%= link_to 'Edit', edit_attendance_path(present) %>
                <%= link_to 'Delete', present, method: :delete, data: { confirm: 'You are going to destroy the record!!! Are you sure?' } %>
              </div>
          <% end %>
        </div>
    <% end %>

    <br><br>
    <div>
      <div class="row-fluid">
        <div class="span2"></div>
        <div class="span10">
          <h2>Absent Employees</h2>
        </div>
      </div>
      <div class="row-fluid">
        <div class="span2"></div>
        <div class="span1"><b>Firstname</b></div>
        <div class="span2"><b>Lastname</b></div>
        <div class="span7"></div>
      </div>

      <% $absent.each do |absent| %>
          <div class="row-fluid">
            <div class="span2"></div>
            <div class="span1"><%= absent.firstname %></div>
            <div class="span2"><%= absent.lastname %></div>

            <% if current_employee.admin %>
                <div class="span2">
                      <%= link_to "Make a Leave",  make_leave_attendances_path( { e_id: absent.to_param } ), :class => "btn btn-default", :style => "margin-top:-1.5%" %>
                </div>
            <% end %>
            <div class="span5"></div>
          </div>
      <% end %>

    </div>
    <br><br>

    <div>
      <div class="row-fluid">
        <div class="span2"></div>
        <div class="span10">
          <h2>On a Leave</h2>
        </div>
      </div>
      <div class="row-fluid">
        <div class="span2"></div>
        <div class="span1"><b>Firstname</b></div>
        <div class="span1"><b>Lastname</b></div>
        <div class="span2"><b>Leave Cause</b></div>
        <div class="span6"></div>
      </div>

      <% @on_leave.each do |leave| %>
          <div class="row-fluid">
            <div class="span2"></div>
            <div class="span1"><%= leave.firstname %></div>
            <div class="span1"><%= leave.lastname %></div>
            <div class="span2"><%= leave.leave_cause %></div>
            <div class="span6"></div>
          </div>
      <% end %>

    </div>
    <br><br>

    <div>
      <div class="row-fluid">
        <div class="span2"></div>
        <div class="span10">
          <h2>All Employees</h2>
        </div>
      </div>
      <div class="row-fluid">
        <div class="span2"></div>
        <div class="span1"><b>Firstname</b></div>
        <div class="span1"><b>Lastname</b></div>
        <div class="span3"><b>Email Address</b></div>
        <div class="span5"></div>
      </div>

      <% @employee.each do |emp| %>
          <div class="row-fluid">
            <div class="span2"></div>
            <div class="span1"><%= emp.firstname %></div>
            <div class="span1"><%= emp.lastname %></div>
            <div class="span3"><%= emp.email %></div>
            <div class="span5"></div>
          </div>
      <% end %>

    </div>
  </div>

</div>

app/views/attendances/make_leave.html.erb
<div>
  <%= render 'header' %>
  <hr>
  <div class="row-fluid">
    <div class="span3"></div>
    <div class="span6" style="text-align: center">
      <h3>Hey, You are going to make a leave for <%= @employee.firstname + " " + @employee.lastname %></h3>
      <%= form_for(@attendance, url: create_leave_attendance_path({ id: @employee.to_param })) do |f| %>
          <% if @attendance.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

                <ul>
                  <% @attendance.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

              <div class="field">
                <%= f.text_field :firstname, :value => @employee.firstname, :readonly => true %>
              </div>
              <div class="field">
                <%= f.text_field :lastname, :value => @employee.lastname, :readonly => true %>
              </div>
              <div class="field">
                <%= f.text_field :email, :value => @employee.email, :readonly => true %>
              </div>
              <div class="field">
                <% date = Time.now.strftime("%d %B %Y").to_s %>
                <%= f.hidden_field :date, :value => date %>
              </div>
              <div class="field">
                <%= f.hidden_field :login_at %>
              </div>
              <div class="field">
                <%= f.hidden_field :logout_at %>
              </div>
              <div class="field">
                <%= f.hidden_field :present, :value => false %>
              </div>
              <div class="field">
                <%= f.hidden_field :leave, :value => true %>
              </div>
              <div class="field">
                <%= f.text_field :leave_cause %>
              </div>
              <div class="actions">
                <%= f.submit "Make Leave", :class => "btn btn-default"%>
              </div>
      <% end %>

    </div>
    <div class="span3"></div>
  </div>
</div>

app/views/attendances/new.html.erb
<div>
  <div class="row-fluid">
    <div class="span3">
      <%= image_tag "ct_logo.png", :style => "margin:8% 0 0 5%" %>
      <b style="margin-left: 6%; font-size: 16px"><%= Time.now.strftime("%A, %d %B %Y") %></b>
    </div>
    <div class="span7"></div>
    <div class="span2">
      Welcome, <b><%= current_employee.firstname %> <%= current_employee.lastname %></b>
      <%= link_to "signout", destroy_employee_session_path, :method => :delete %>
    </div>
  </div>
  <hr>
  <div class="row-fluid">
    <div class="span3"></div>
    <div class="span6" style="text-align: center">
      <h3>Hey <%= current_employee.firstname %>, Good Morning. Have a Good day!!! :)</h3>
      <%= render 'form' %>
    </div>
    <div class="span3"></div>
  </div>
</div>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @attendance.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @attendance.lastname %>
</p>

<p>
  <strong>Date:</strong>
  <%= @attendance.date %>
</p>

<p>
  <strong>Login at:</strong>
  <%= @attendance.login_at %>
</p>

<p>
  <strong>Logout at:</strong>
  <%= @attendance.logout_at %>
</p>

<p>
  <strong>Present:</strong>
  <%= @attendance.present %>
</p>

<p>
  <strong>Leave:</strong>
  <%= @attendance.leave %>
</p>

<p>
  <strong>Leave cause:</strong>
  <%= @attendance.leave_cause %>
</p>

<p>
  <strong>Working hours:</strong>
  <%= @attendance.working_hours %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>CodersTrust BD | Employee Attendance System</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>